nodeLinker: node-modules

npmRegistries:
  //gitlab.com/api/v4/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: ${GITLAB_TOKEN:a}

npmScopes:
  kosygin-rsu:
    npmRegistryServer: 'https://gitlab.com/api/v4/packages/npm/'
